services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stockea
      POSTGRES_PASSWORD: stockea
      POSTGRES_DB: stockea
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
