// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (project_id, name, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, color, icon
`

type CreateCategoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	Icon      pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Icon,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE project_id = $1 AND id = $2
`

type DeleteCategoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Los productos de esta categoría se quedan sin categoría (ON DELETE SET NULL)
func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, project_id, name, color, icon FROM categories WHERE project_id = $1 AND id = $2
`

type GetCategoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ProjectID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Icon,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT c.id, c.project_id, c.name, c.color, c.icon, count(p.id)::int AS product_count
FROM categories c
LEFT JOIN products p ON p.category_id = c.id
WHERE c.project_id = $1
GROUP BY c.id
ORDER BY c.name
`

type ListCategoriesRow struct {
	ID           pgtype.UUID `json:"id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	Name         string      `json:"name"`
	Color        string      `json:"color"`
	Icon         pgtype.Text `json:"icon"`
	ProductCount int32       `json:"product_count"`
}

// Todas las consultas filtran por project_id: así es imposible tocar datos de otro proyecto
// aunque alguien ponga en la URL el id de una categoría ajena.
func (q *Queries) ListCategories(ctx context.Context, projectID pgtype.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $3, color = $4, icon = $5
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, name, color, icon
`

type UpdateCategoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	Icon      pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Icon,
	)
	return i, err
}
