// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (project_id, parent_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, parent_id, name, description, qr_code
`

type CreateLocationParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ProjectID,
		arg.ParentID,
		arg.Name,
		arg.Description,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.QrCode,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations WHERE project_id = $1 AND id = $2
`

type DeleteLocationParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Las sububicaciones pasan a no tener padre y los productos se quedan sin ubicación
func (q *Queries) DeleteLocation(ctx context.Context, arg DeleteLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocation, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLocation = `-- name: GetLocation :one
SELECT id, project_id, parent_id, name, description, qr_code FROM locations WHERE project_id = $1 AND id = $2
`

type GetLocationParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ProjectID, arg.ID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.QrCode,
	)
	return i, err
}

const isLocationOrDescendant = `-- name: IsLocationOrDescendant :one
WITH RECURSIVE subtree(loc_id) AS (
    SELECT $2::uuid
    UNION
    SELECT c.id FROM locations c JOIN subtree ON c.parent_id = subtree.loc_id
)
SELECT EXISTS (SELECT 1 FROM subtree WHERE loc_id = $1::uuid)::bool
`

type IsLocationOrDescendantParams struct {
	Candidate pgtype.UUID `json:"candidate"`
	ID        pgtype.UUID `json:"id"`
}

// ¿Es `candidate` la propia ubicación `id` o una de sus descendientes?
// Sirve para impedir ciclos (Caja 3 dentro de Estantería A dentro de Caja 3...).
func (q *Queries) IsLocationOrDescendant(ctx context.Context, arg IsLocationOrDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLocationOrDescendant, arg.Candidate, arg.ID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listLocations = `-- name: ListLocations :many
SELECT l.id, l.project_id, l.parent_id, l.name, l.description, l.qr_code, count(p.id)::int AS product_count
FROM locations l
LEFT JOIN products p ON p.location_id = l.id
WHERE l.project_id = $1
GROUP BY l.id
ORDER BY l.name
`

type ListLocationsRow struct {
	ID           pgtype.UUID `json:"id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	QrCode       pgtype.Text `json:"qr_code"`
	ProductCount int32       `json:"product_count"`
}

func (q *Queries) ListLocations(ctx context.Context, projectID pgtype.UUID) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.QrCode,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET parent_id = $3, name = $4, description = $5
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, parent_id, name, description, qr_code
`

type UpdateLocationParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ProjectID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Description,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.QrCode,
	)
	return i, err
}
