// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MovementType string

const (
	MovementTypeIn     MovementType = "in"
	MovementTypeOut    MovementType = "out"
	MovementTypeAdjust MovementType = "adjust"
)

func (e *MovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementType(s)
	case string:
		*e = MovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementType: %T", src)
	}
	return nil
}

type NullMovementType struct {
	MovementType MovementType `json:"movement_type"`
	Valid        bool         `json:"valid"` // Valid is true if MovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.MovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementType), nil
}

type ProjectRole string

const (
	ProjectRoleEditor ProjectRole = "editor"
	ProjectRoleViewer ProjectRole = "viewer"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"project_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type Category struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	Icon      pgtype.Text `json:"icon"`
}

type Location struct {
	ID          pgtype.UUID `json:"id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	QrCode      pgtype.Text `json:"qr_code"`
}

type Movement struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      MovementType       `json:"type"`
	Quantity  int32              `json:"quantity"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	LocationID  pgtype.UUID        `json:"location_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Quantity    int32              `json:"quantity"`
	Unit        string             `json:"unit"`
	MinQuantity int32              `json:"min_quantity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProductPhoto struct {
	ID         pgtype.UUID        `json:"id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	StorageKey string             `json:"storage_key"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
