// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovement = `-- name: CreateMovement :one
INSERT INTO movements (product_id, user_id, type, quantity, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, user_id, type, quantity, reason, created_at
`

type CreateMovementParams struct {
	ProductID pgtype.UUID  `json:"product_id"`
	UserID    pgtype.UUID  `json:"user_id"`
	Type      MovementType `json:"type"`
	Quantity  int32        `json:"quantity"`
	Reason    pgtype.Text  `json:"reason"`
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) (Movement, error) {
	row := q.db.QueryRow(ctx, createMovement,
		arg.ProductID,
		arg.UserID,
		arg.Type,
		arg.Quantity,
		arg.Reason,
	)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listMovements = `-- name: ListMovements :many
SELECT m.id, m.product_id, m.user_id, m.type, m.quantity, m.reason, m.created_at,
       p.name AS product_name,
       p.unit AS product_unit,
       u.name AS user_name
FROM movements m
JOIN products p ON p.id = m.product_id
JOIN users    u ON u.id = m.user_id
WHERE p.project_id = $1
  AND ($2::uuid IS NULL OR m.product_id = $2)
  AND ($3::movement_type IS NULL OR m.type = $3)
ORDER BY m.created_at DESC
LIMIT $5 OFFSET $4
`

type ListMovementsParams struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	ProductID pgtype.UUID      `json:"product_id"`
	Type      NullMovementType `json:"type"`
	SkipRows  int32            `json:"skip_rows"`
	MaxRows   int32            `json:"max_rows"`
}

type ListMovementsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Type        MovementType       `json:"type"`
	Quantity    int32              `json:"quantity"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProductName string             `json:"product_name"`
	ProductUnit string             `json:"product_unit"`
	UserName    string             `json:"user_name"`
}

// Historial del proyecto (o de un producto), lo más reciente primero.
func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.ProjectID,
		arg.ProductID,
		arg.Type,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovementsRow
	for rows.Next() {
		var i ListMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Type,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductUnit,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
