// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductPhotos = `-- name: CountProductPhotos :one
SELECT count(*)::int FROM product_photos WHERE product_id = $1
`

func (q *Queries) CountProductPhotos(ctx context.Context, productID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProductPhotos, productID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProductPhoto = `-- name: CreateProductPhoto :one
INSERT INTO product_photos (product_id, storage_key, position)
VALUES ($1, $2, $3)
RETURNING id, product_id, storage_key, position, created_at
`

type CreateProductPhotoParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	StorageKey string      `json:"storage_key"`
	Position   int32       `json:"position"`
}

func (q *Queries) CreateProductPhoto(ctx context.Context, arg CreateProductPhotoParams) (ProductPhoto, error) {
	row := q.db.QueryRow(ctx, createProductPhoto, arg.ProductID, arg.StorageKey, arg.Position)
	var i ProductPhoto
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductPhoto = `-- name: DeleteProductPhoto :exec
DELETE FROM product_photos WHERE id = $1
`

func (q *Queries) DeleteProductPhoto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductPhoto, id)
	return err
}

const getProductPhoto = `-- name: GetProductPhoto :one
SELECT ph.id, ph.product_id, ph.storage_key, ph.position, ph.created_at FROM product_photos ph
JOIN products p ON p.id = ph.product_id
WHERE p.project_id = $1 AND ph.product_id = $2 AND ph.id = $3
`

type GetProductPhotoParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ProductID pgtype.UUID `json:"product_id"`
	ID        pgtype.UUID `json:"id"`
}

// Comprueba a la vez que la foto es de ese producto y el producto de ese proyecto
func (q *Queries) GetProductPhoto(ctx context.Context, arg GetProductPhotoParams) (ProductPhoto, error) {
	row := q.db.QueryRow(ctx, getProductPhoto, arg.ProjectID, arg.ProductID, arg.ID)
	var i ProductPhoto
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listProductPhotos = `-- name: ListProductPhotos :many
SELECT id, product_id, storage_key, position, created_at FROM product_photos
WHERE product_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListProductPhotos(ctx context.Context, productID pgtype.UUID) ([]ProductPhoto, error) {
	rows, err := q.db.Query(ctx, listProductPhotos, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductPhoto
	for rows.Next() {
		var i ProductPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StorageKey,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
