// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (project_id, category_id, location_id, name, description, unit, min_quantity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at
`

type CreateProductParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	LocationID  pgtype.UUID `json:"location_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Unit        string      `json:"unit"`
	MinQuantity int32       `json:"min_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProjectID,
		arg.CategoryID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.MinQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE project_id = $1 AND id = $2
`

type DeleteProductParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Borra también sus movimientos y fotos (ON DELETE CASCADE)
func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductDetail = `-- name: GetProductDetail :one
SELECT p.id, p.project_id, p.category_id, p.location_id, p.name, p.description, p.quantity, p.unit, p.min_quantity, p.created_at, p.updated_at,
       c.name  AS category_name,
       c.color AS category_color,
       c.icon  AS category_icon,
       l.name  AS location_name,
       (SELECT ph.id FROM product_photos ph
        WHERE ph.product_id = p.id
        ORDER BY ph.position, ph.created_at
        LIMIT 1)::uuid AS cover_photo_id
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN locations  l ON l.id = p.location_id
WHERE p.project_id = $1 AND p.id = $2
`

type GetProductDetailParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

type GetProductDetailRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	LocationID    pgtype.UUID        `json:"location_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Quantity      int32              `json:"quantity"`
	Unit          string             `json:"unit"`
	MinQuantity   int32              `json:"min_quantity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  pgtype.Text        `json:"category_name"`
	CategoryColor pgtype.Text        `json:"category_color"`
	CategoryIcon  pgtype.Text        `json:"category_icon"`
	LocationName  pgtype.Text        `json:"location_name"`
	CoverPhotoID  pgtype.UUID        `json:"cover_photo_id"`
}

func (q *Queries) GetProductDetail(ctx context.Context, arg GetProductDetailParams) (GetProductDetailRow, error) {
	row := q.db.QueryRow(ctx, getProductDetail, arg.ProjectID, arg.ID)
	var i GetProductDetailRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.CategoryIcon,
		&i.LocationName,
		&i.CoverPhotoID,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at FROM products WHERE project_id = $1 AND id = $2 FOR UPDATE
`

type GetProductForUpdateParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Bloquea la fila hasta que termine la transacción: si dos personas registran
// una salida a la vez, la segunda espera y ve el stock ya actualizado.
func (q *Queries) GetProductForUpdate(ctx context.Context, arg GetProductForUpdateParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, arg.ProjectID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsForUpdate = `-- name: GetProductsForUpdate :many
SELECT id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at FROM products
WHERE project_id = $1 AND id = ANY($2::uuid[])
ORDER BY id
FOR UPDATE
`

type GetProductsForUpdateParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

// Bloquea varios productos a la vez, SIEMPRE en el mismo orden (por id):
// si dos salidas múltiples coinciden, ninguna se queda esperando a la otra para siempre (deadlock).
func (q *Queries) GetProductsForUpdate(ctx context.Context, arg GetProductsForUpdateParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsForUpdate, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.MinQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.project_id, p.category_id, p.location_id, p.name, p.description, p.quantity, p.unit, p.min_quantity, p.created_at, p.updated_at,
       c.name  AS category_name,
       c.color AS category_color,
       c.icon  AS category_icon,
       l.name  AS location_name,
       (SELECT ph.id FROM product_photos ph
        WHERE ph.product_id = p.id
        ORDER BY ph.position, ph.created_at
        LIMIT 1)::uuid AS cover_photo_id
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN locations  l ON l.id = p.location_id
WHERE p.project_id = $1
  AND ($2::uuid IS NULL OR p.category_id = $2)
  AND ($3::uuid IS NULL OR p.location_id = $3)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%')
  AND (NOT $5::bool OR p.quantity <= p.min_quantity)
ORDER BY p.name
`

type ListProductsParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	LocationID   pgtype.UUID `json:"location_id"`
	Search       pgtype.Text `json:"search"`
	LowStockOnly bool        `json:"low_stock_only"`
}

type ListProductsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	LocationID    pgtype.UUID        `json:"location_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Quantity      int32              `json:"quantity"`
	Unit          string             `json:"unit"`
	MinQuantity   int32              `json:"min_quantity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  pgtype.Text        `json:"category_name"`
	CategoryColor pgtype.Text        `json:"category_color"`
	CategoryIcon  pgtype.Text        `json:"category_icon"`
	LocationName  pgtype.Text        `json:"location_name"`
	CoverPhotoID  pgtype.UUID        `json:"cover_photo_id"`
}

// Listado con filtros opcionales: cada filtro se ignora si llega NULL.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.ProjectID,
		arg.CategoryID,
		arg.LocationID,
		arg.Search,
		arg.LowStockOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.MinQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.LocationName,
			&i.CoverPhotoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductQuantity = `-- name: SetProductQuantity :exec
UPDATE products SET quantity = $2, updated_at = now() WHERE id = $1
`

type SetProductQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) SetProductQuantity(ctx context.Context, arg SetProductQuantityParams) error {
	_, err := q.db.Exec(ctx, setProductQuantity, arg.ID, arg.Quantity)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $3, location_id = $4, name = $5, description = $6,
    unit = $7, min_quantity = $8, updated_at = now()
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at
`

type UpdateProductParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ID          pgtype.UUID `json:"id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	LocationID  pgtype.UUID `json:"location_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Unit        string      `json:"unit"`
	MinQuantity int32       `json:"min_quantity"`
}

// Edita los datos del producto. La cantidad NO se toca aquí: solo cambia con movimientos.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProjectID,
		arg.ID,
		arg.CategoryID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.MinQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
