// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyStockDelta = `-- name: ApplyStockDelta :one
UPDATE products
SET quantity = quantity + $1, updated_at = now()
WHERE id = $2
RETURNING id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at
`

type ApplyStockDeltaParams struct {
	Delta int32       `json:"delta"`
	ID    pgtype.UUID `json:"id"`
}

// Cambiar stock: estas dos consultas se ejecutan SIEMPRE juntas en una transacción
func (q *Queries) ApplyStockDelta(ctx context.Context, arg ApplyStockDeltaParams) (Product, error) {
	row := q.db.QueryRow(ctx, applyStockDelta, arg.Delta, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMovement = `-- name: CreateMovement :one
INSERT INTO movements (product_id, user_id, type, quantity, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, user_id, type, quantity, reason, created_at
`

type CreateMovementParams struct {
	ProductID pgtype.UUID  `json:"product_id"`
	UserID    pgtype.UUID  `json:"user_id"`
	Type      MovementType `json:"type"`
	Quantity  int32        `json:"quantity"`
	Reason    pgtype.Text  `json:"reason"`
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) (Movement, error) {
	row := q.db.QueryRow(ctx, createMovement,
		arg.ProductID,
		arg.UserID,
		arg.Type,
		arg.Quantity,
		arg.Reason,
	)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Type,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (project_id, category_id, location_id, name, description, unit, min_quantity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at
`

type CreateProductParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	LocationID  pgtype.UUID `json:"location_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Unit        string      `json:"unit"`
	MinQuantity int32       `json:"min_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProjectID,
		arg.CategoryID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.MinQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CategoryID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.MinQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLowStock = `-- name: ListLowStock :many
SELECT id, project_id, category_id, location_id, name, description, quantity, unit, min_quantity, created_at, updated_at FROM products
WHERE project_id = $1 AND quantity <= min_quantity
ORDER BY name
`

func (q *Queries) ListLowStock(ctx context.Context, projectID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listLowStock, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.MinQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT m.id, m.product_id, m.user_id, m.type, m.quantity, m.reason, m.created_at, u.name AS user_name
FROM movements m
JOIN users u ON u.id = m.user_id
WHERE m.product_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListMovementsParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Limit     int32       `json:"limit"`
}

type ListMovementsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      MovementType       `json:"type"`
	Quantity  int32              `json:"quantity"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error) {
	rows, err := q.db.Query(ctx, listMovements, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovementsRow
	for rows.Next() {
		var i ListMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Type,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.project_id, p.category_id, p.location_id, p.name, p.description, p.quantity, p.unit, p.min_quantity, p.created_at, p.updated_at, c.name AS category_name, l.name AS location_name
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN locations  l ON l.id = p.location_id
WHERE p.project_id = $1
ORDER BY p.name
`

type ListProductsRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	LocationID   pgtype.UUID        `json:"location_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Quantity     int32              `json:"quantity"`
	Unit         string             `json:"unit"`
	MinQuantity  int32              `json:"min_quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName pgtype.Text        `json:"category_name"`
	LocationName pgtype.Text        `json:"location_name"`
}

func (q *Queries) ListProducts(ctx context.Context, projectID pgtype.UUID) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.MinQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
